### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by lcl-367** [moqsien/gvc#10]
Java 复制的是jre下的bin和lib，能否更换成jdk下的全部并指定两个bin的path？同时希望可以支持选择小版本，而不只是8，17，21之类的最新版本

**Comment by moqsien** [comment]
> Java 复制的是jre下的bin和lib，能否更换成jdk下的全部并指定两个bin的path？同时希望可以支持选择小版本，而不只是8，17，21之类的最新版本

版本管理器迁移到新的通用版本管理器[vm](https://github.com/gvcgo/version-manager)，欢迎使用，star，pr，issue。
