### ISSUE TITLE
github.com/j178/chatgpt should be mentioned

### ISSUE THREAD

**Issue by j178** [moqsien/gvc#2]
Hi there,

I noticed that some code about chatgpt of this repo appears to have been taken from mine at https://github.com/j178/chatgpt. While I'm glad to see that my work has been helpful to you, I kindly request that you acknowledge the original source by adding a simple thank you note or a reference to my repository in your project documentation.

Thank you.

**Comment by moqsien** [comment]
[chatgpt](https://github.com/j178/chatgpt) will be added to the ThanksTo after the chatgpt feature become available in gvc.
