### ISSUE TITLE
macos arm64, go下载老版本失败后, 会使得go链接到错误的目录

### ISSUE THREAD

**Issue by yifhao** [moqsien/gvc#3]
<img width="928" alt="image" src="https://user-images.githubusercontent.com/12428110/233825832-59445751-38a2-4190-8383-475d6f45752a.png">

后面的设置别的版本也不能成功, 需要手动删除这个go链接.
看了下应该是因为1.16才提供macos arm64. 
对于下载错误, 应该判断返回失败, 不进行后续的设置

**Comment by yifhao** [comment]
#4

**Comment by moqsien** [comment]
OK，非常感谢，晚点会修复。
