### ISSUE TITLE
请求支持一下ziglang

### ISSUE THREAD

**Issue by vicnoah** [moqsien/gvc#7]
gvc很好用也支持了很多语言的管理，最近zig比较火但发现gvc不支持zig。希望能够支持一下zig语言

**Comment by moqsien** [comment]
> gvc很好用也支持了很多语言的管理，最近zig比较火但发现gvc不支持zig。希望能够支持一下zig语言

很好的建议。
但是最近没有计划。在做其他事情。后面可以考虑。
另外，如果有能力和兴趣，欢迎贡献相关代码。

**Comment by vicnoah** [comment]
> > gvc很好用也支持了很多语言的管理，最近zig比较火但发现gvc不支持zig。希望能够支持一下zig语言
> 
> 很好的建议。
> 但是最近没有计划。在做其他事情。后面可以考虑。
> 另外，如果有能力和兴趣，欢迎贡献相关代码。
> 

好的，我有时间的话我也会尝试实现一下。
