### ISSUE TITLE
建议增加包目录 自定义

### ISSUE THREAD

**Issue by lixi94** [moqsien/gvc#9]
建议增加包目录 自定义

**Comment by moqsien** [comment]
> 建议增加包目录 自定义

已有自定义包目录。

包目录，指的是几乎所有的通过gvc安装的软件的存放目录，即AppDir。

AppDir会在你首次运行和安装gvc的时候提示进行设置，用户可以输入自己想要指定的文件夹。如果输入为空，则默认与gvc的安装目录相同。

注意，gvc的安装目录无法指定。安装目录默认为~/.gvc/（windows用户的~目录一般为当前用户对应的文件夹）。

具体请参考：
[文档](https://github.com/moqsien/gvc/wiki/%E4%B8%AD%E6%96%87)

**Comment by lixi94** [comment]
我的意思比如，  GO 的path和bin目录，可以自定义， 你全默认到C盘，到时候包多了，文件占地方。

**Comment by moqsien** [comment]
> 我的意思比如， GO 的path和bin目录，可以自定义， 你全默认到C盘，到时候包多了，文件占地方。

$GOPATH和$GOBIN下的这些代码和可执行文件应该占不了多少。如果之前没安装过go，系统里没有这些环境变量，会默认放到~/data/projects/go/下面。如果你的系统上原先安装有go的话，默认会使用原先的配置。

主要是安装文件的AppDir，占用会比较多。AppDir是各种编译器及其他软件的安装目录。

若很多人有这样的需求，后面可以考虑加入可配置项。
